raccord-io/ui-kit

presets/raccord-preset.js, src/components/ThemeMode/ThemeMode.stories.tsx, src/components/ThemeMode/ThemeMode.test.tsx, src/components/ThemeMode/ThemeMode.tsx, src/components/ThemeMode/index.ts, src/global.css
We are adding `ThemeMode` component.
=> add theme mode component

src/components/index.ts
We are adding missing export for `ThemeMode` component.
=> add missing export

src/components/ThemeMode/ThemeMode.tsx, src/util/useLocalStorage.ts
We are fixing error on localestorage custom hook.
=> fix error for local storage

presets/raccord-preset.js
We are adding `rac-h1` and `rac-body` custom css class.
=> feat(class): add custom css class

presets/raccord-preset.js, src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.test.tsx, src/components/Tag/Tag.tsx, src/components/Tag/index.ts, src/components/index.ts
We are implementing a new `Component` named `Tag`.
=> feat(tag): implement tag component

package-lock.json, package.json
We are updating `react-icons` package.s
=> update react-icons package

src/components/SideBar/SideBar.stories.tsx, src/components/SideBar/SideBar.test.tsx, src/components/SideBar/SideBar.tsx, src/components/SideBar/index.ts, src/components/index.ts
We are implementing `SideBar` component in the `ui-kit`.
=> feat(sidebar): implement sidebar component

src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/index.ts, src/components/index.ts
We are implementing `Pagination` component.
=> implement pagination component

src/components/SideBar/SideBar.stories.tsx, src/components/SideBar/SideBar.tsx
We are implementing a new feature in `Sidebar` component to click on text `Voir les informations`.
=> feat(Sidebar): added onClick informations

src/components/Toggle/Toggle.stories.tsx, src/components/Toggle/Toggle.test.tsx, src/components/Toggle/Toggle.tsx, src/components/Toggle/index.ts
=> feat(Toggle): created a new Toggle component

src/components/Password/Password.stories.tsx, src/components/Password/Password.test.tsx, src/components/Password/Password.tsx, src/components/Password/index.ts
=> feat(Password): created a Password component for password inputs

jest.config.cjs, package-lock.json, package.json, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, tsconfig.json, vite.config.ts
We are updating properties from component `Button` to use `buttonVariants` props.
We are also adding absolute path `@/` in the config file.
=> update(button): update properties

package-lock.json, package.json, src/components/ScrollArea/ScrollArea.stories.tsx, src/components/ScrollArea/ScrollArea.test.tsx, src/components/ScrollArea/ScrollArea.tsx, src/components/ScrollArea/index.ts, src/components/index.ts
We are adding a new component named: `ScrollArea`.
=> feat(component): added scrollArea component

src/components/ScrollArea/ScrollArea.tsx
We are removing border on `ScrollBar`.
=> remove border on scrollbar

src/components/Input/Input.stories.tsx, src/components/Input/Input.tsx, src/components/Password/Password.tsx, src/components/index.ts
We are fixing `ref` for components `Input` & `Password`.
=> fix ref for components input & password

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx
We are removing text on hover for `ButtonIcon`.
=> remove button icon

src/components/Card/Card.stories.tsx, src/components/Card/Card.tsx, src/components/Identicon/Identicon.stories.tsx, src/components/Identicon/Identicon.tsx, src/components/Popover/Popover.stories.tsx, src/components/PopupModal/PopupModal.stories.tsx, src/components/PopupModal/PopupModal.tsx
We are updating some components ref:
- `Card`,
- `PopupModal`,
- `Identicon`
=> update components ref

src/components/Card/Card.tsx, src/components/Identicon/Identicon.tsx
We are updating:
- `p-4` is removed from component `Card`.
- `rounded-md` -> `rounded-sm` from component `Identicon`.
=> update padding & radius

src/components/NavItem/NavItem.stories.tsx, src/components/NavItem/NavItem.tsx, src/components/NavItem/index.ts, src/components/index.ts
We are adding a new component `NavItem`.
=> added new component navitem

src/components/NavItem/NavItem.tsx, src/components/PopupModal/PopupModal.stories.tsx, src/components/PopupModal/PopupModal.tsx
We are updating `z-index` and scroll.
=> update modal z-index and scroll

src/components/PopupModal/PopupModal.tsx
We are removing stop scroll when `PopUpModal` is open.
=> removed stop scroll when modal is open

src/components/NavItem/NavItem.stories.tsx, src/components/NavItem/NavItem.tsx
We are adding a param `open` in the `NavItem` component.
=> add param open in navitem component

src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.test.tsx, src/components/Tag/Tag.tsx
We are updating component `Tag`.
=> updated tag component

package-lock.json, package.json, src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/index.ts, src/components/index.ts
We are adding component `Checkbox`.
=> feat(checkbox): added new component

src/components/Password/Password.stories.tsx, src/components/Password/Password.tsx
We are fixing `width` of the input.
=> fix(Password): fix width

src/components/Avatar/Avatar.tsx, src/components/Badge/Badge.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Button/Button.tsx, src/components/Card/Card.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Dialog/Dialog.tsx, src/components/DropZone/DropZone.tsx, src/components/DropdownMenu/DropdownMenu.tsx, src/components/Identicon/Identicon.tsx, src/components/Input/Input.tsx, src/components/Label/Label.tsx, src/components/Loader/Loader.tsx, src/components/Menubar/Menubar.tsx, src/components/Pagination/Pagination.tsx, src/components/Password/Password.tsx, src/components/Popover/Popover.tsx, src/components/ScrollArea/ScrollArea.tsx, src/components/Select/Select.tsx, src/components/Separator/Separator.tsx, src/components/Sheet/Sheet.tsx, src/components/Sidebar/Sidebar.tsx, src/components/Skeleton/Skeleton.tsx, src/components/Stepper/Stepper.tsx, src/components/Table/Table.tsx, src/components/Tabs/Tabs.tsx, src/components/TextArea/TextArea.tsx, src/components/Tooltip/Tooltip.tsx
=> feat(path): remaned path symbol
